config/routes.rb
GentlemansBet::Application.routes.draw do

  resources :users, :only => [] do
    resources :challenges, :only => [:index, :create]
  end

  resources :challenges, :only => [:show, :update]

  root 'twitters#index'
  get 'login' => 'twitters#new'
  get 'auth' => 'twitters#auth'
  delete 'sign_out' => 'twitters#sign_out'
  get 'about' => 'navbars#about'

end

app/models/challenge.rb
class Challenge < ActiveRecord::Base
	belongs_to :challenger, class_name: "User", foreign_key: "challenger_id"
	belongs_to :challengee, class_name: "User", foreign_key: "challengee_id"
	belongs_to :winner, class_name: "User", foreign_key: "winner_id"
	belongs_to :status
  validates :title, :terms, :reward, :end_date, :challengee_id, :presence => true
  validate :end_date_validity

  def end_date_validity
    if end_date 
      errors.add(:end_date, "can't be in the past") if end_date < Date.today
    end
  end

  def obtain_bitly_url(url)
    long_url = URI::encode(url)
    access_token = obtain_bitly_access_token
    request_to_bitly = URI.parse("https://api-ssl.bitly.com/v3/shorten?access_token=#{access_token}&longUrl=#{long_url}")
    bitly_response = Net::HTTP.get_response(request_to_bitly)
    self.bitly_url = JSON.parse(bitly_response.body)['data']['url']
    self.save
  end

  def update_winner(user)
    self.challenger == user ? self.winner_id = self.challengee.id : self.winner_id = self.challenger.id
    self.status_id = 4
    self.save
  end

  def issue
    "@"+self.challengee.username + ", You have been Challenged! " + self.title + ":" + self.bitly_url + " #gmbet"
  end

  def concede
    "@"+self.winner.username + ", Fine, I concede you are the greatest in the universe. " + self.title + ":" + self.bitly_url + " #gmbet"
  end

  def response
    "@"+self.challenger.username + ", your challenge has been " + self.status.condition + ".  " + self.bitly_url + " #gmbet"
  end

  private

  def obtain_bitly_access_token
    uri = URI.parse("https://api-ssl.bitly.com/oauth/access_token")
    req = Net::HTTP::Post.new(uri.path)
    req.basic_auth(ENV['CLIENT_ID'],ENV['CLIENT_SECRET'])
    req.set_form_data({"grant_type" => "password", "username" => ENV['USERNAME'], "password" => ENV['PASSWORD']})
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    response = http.start {|http| http.request(req) }
    access_token = JSON.parse(response.body)["access_token"]
  end
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  def index
    @errors = nil
    @user = User.new
    @challenge = Challenge.new
    if session[:user_id] == params[:user_id].to_i
      @challenges_created = current_user.challenges_created
      @challenges_received = current_user.challenges_received
    elsif session[:user_id] != nil
      render :status => 401
    else
      redirect_to :root
    end
  end

  def create
    @challenge = Challenge.new(challenge_params)
    if @challenge.save
      @challenge.obtain_bitly_url(challenge_url(@challenge))
      current_user.tweet(@challenge.issue)
      redirect_to user_challenges_path(current_user)
    else
      @user = User.new(username: params[:user][:username])
      @errors = @challenge.errors.full_messages
      @challenges_created = current_user.challenges_created
      @challenges_received = current_user.challenges_received
      render "index"
    end
  end

  def show
    if session[:user_id]
      @current_user = current_user
      @challenge = Challenge.find(params[:id])
    else
      session[:origin] = request.original_url
      redirect_to "/login"
    end
  end

  def update
    challenge = Challenge.find(params[:id])
    if params[:status_id] 
      challenge.status_id = params[:status_id]
      challenge.save
      current_user.tweet(challenge.response)
      redirect_to user_challenges_path(current_user)
    else
      challenge.update_winner(current_user)
      current_user.tweet(challenge.concede)
      redirect_to user_challenges_path(current_user)
    end
  end

  private

  def challenge_params
    params[:challenge][:challenger_id] = current_user.id
    params[:challenge][:status_id] = 1
    challengee = User.find_or_create_by(username: params[:user][:username].downcase)
    params[:challenge][:challengee_id] = challengee.id
    params.required(:challenge).permit(:title, :terms, :reward, :end_date, :challenger_id, :challengee_id, :status_id)
  end
end

app/views/challenges/index.html.erb
<div id="page">

  <%= form_for [:user,@challenge], :html => {id: "create"} do |f| %>
  <h2>Create a Challenge</h2>
  <ul>
    <li>
      <%= f.text_field :title, placeholder: "Title" %>
    </li>
    <%= fields_for @user do |u| %>
        <li>
          <%= u.text_field :username, placeholder: "Challengee Username" %>
        </li>
    <% end %>
    <li>
      <%= f.text_area :terms, size: "30x5", placeholder: "Terms" %>
    </li>
    <li>
      <%= f.text_field :reward, placeholder: "Reward" %>
    </li>
    <li>
      <%= f.label :end_date, "End Date"%>
    </li>
    <li>
      <%= f.date_field :end_date %>
    </li>
    <li><%= f.submit "Send Challenge", id: "button_style2" %></li>
  </ul>
  <% if @errors %>
    <ul class="errors">
      <% @errors.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <% end %>
  <div id="challenges">
    <h3>Challenges Created</h3>
    <table>
     <tr><th>Challenge Title</th><th>End Date</th><th>Challengee</th><th>Status</th><th>Winner</th></tr>
    <% @challenges_created.each do |challenge| %>
        <tr><td><%=link_to challenge.title, challenge_path(challenge)%></td><td><%=date_display(challenge.end_date)%></td><td><%=challenge.challengee.username%></td><td><%=challenge.status.condition%></td><td><%=challenge.winner.username unless challenge.winner.nil?%></td></tr>
      <% end %>
    </table>
    <h3>Challenges Received</h3>
    <table>
      <tr><th>Challenge Title</th><th>End Date</th><th>Challenger</th><th>Status</th><th>Winner</th></tr>
      <% @challenges_received.each do |challenge| %>
        <tr><td><%=link_to challenge.title, challenge_path(challenge)%></td><td><%=date_display(challenge.end_date)%></td><td><%=challenge.challenger.username%></td><td><%=challenge.status.condition%></td><td><%=challenge.winner.username unless challenge.winner.nil?%></td></tr>
      <% end %>
    </table>
  </div>

</div>

app/views/challenges/new.html.erb
<%= form_for @challenge do |f| %>
  <p>
    <%= f.label "Name your challenge:", :title %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label "Name your terms:", :terms %>
    <%= f.text_field :terms %>
  </p>
  <p>
    <%= f.label "Name your reward:", :reward %>
    <%= f.text_field :reward %>
  </p>
  <p>
    <%= f.label "Name your deadline:", :end_date %>
    <%= f.text_field :end_date %>
  </p>
  <p>
    <%= f.label "Who are you challenging (their Twitter handle)?:", :challengee_handle %>
    <%= f.text_field :challengee_handle %>
  </p>
  <p>
    <%= f.submit "Place your bet" %>
  </p>

<% end %>

app/views/challenges/show.html.erb
<div id="page">
	<div id="display">
		<h3><%=@challenge.title.capitalize%></h3>
		<h5>Reward: <%=@challenge.reward%></h5>
		<h5>End Date: <%=date_display(@challenge.end_date)%></h5>
		<h4><%=@challenge.challenger.username%> vs <%=@challenge.challengee.username%></h4>
		<h5>Status: <%=@challenge.status.condition%></h5>
		<% if @challenge.winner %>
		  <h5>Winner: <%=@challenge.winner.username%></h5>
		<% end %>
		<h5>Terms</h5>
		<p><%=@challenge.terms%></p>
	</div>
	<div id="options">
		<% if @current_user.id == @challenge.challengee_id && @challenge.status.condition == "Pending"%>
		  <%= button_to 'Sir (or Lady), I do declare that I shall meet those terms.', {:controller => "challenges", :action => "update", :status_id => 2}, :method=>:put, class: "button_style3"%>
		  <%= button_to 'Your wager is beneath me.', {:controller => "challenges", :action => "update", :status_id => 3}, :method=>:put, class: "button_style3"%>
		<% elsif @current_user.id == @challenge.challenger_id && @challenge.status.condition == "Accepted" && @challenge.winner_id.nil? || @current_user.id == @challenge.challengee_id && @challenge.status.condition == "Accepted" && @challenge.winner_id.nil?%>
		  <%= button_to 'Concede', {:controller => "challenges", :action => "update", :concede => "Y"}, :method=>:put,class: "button_style3"  %>
		<% elsif @current_user.id %>
		  <%=link_to "Issue a Challenge", user_challenges_path(@current_user)%>
		<% end %>
	</div>
</div>